version: "3.0"

services:
  app:
    image: node:18.16-alpine
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm run start:dev
    depends_on:
      - mongo

  mongo:
    image: mongo